version: '3'
services:
  laravel-app:
    build:
      context: .
    depends_on:
      - redis
    ports:
      - "8080:80"
    networks:
      - common-network
  redis:
    image: redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    networks:
      - common-network
networks:
  common-network:
