version: '3'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - my_network

  redis:
    image: "redis:latest"
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    networks:
      - my_network
      
networks:
  my_network:
