version: '3'
services:
  laravel-app:
    build:
      context: .
    depends_on:
      - redis
    ports:
      - "9000:9000"  # Mapeie a porta 80 do contêiner para a porta 8080 do host
    dns:
      - 1.1.1.1  # Configuração de DNS personalizado
  redis:
    image: redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
