version: '3'
services:
  laravel-app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
  redis:
    image: redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
