version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "9000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/var/www/html
      - /etc/letsencrypt
    depends_on:
      - php-fpm
    networks:
      - my_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot-webroot:/var/www/certbot
      - /etc/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email gustavo.ribeiro@software-solution-it.com --agree-tos --no-eff-email -d betxoficial.com
    networks:
      - my_network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    networks:
      - my_network

  redis:
    image: "redis:latest"
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    networks:
      - my_network
      
networks:
  my_network:
