version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "9000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - my_network

  php-fpm:
    image: php:7.4-fpm
    volumes:
      - ./:/var/www/html
    networks:
      - my_network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  my_network:
