version: '3'
services:
  laravel-app:
    build:
      context: .
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./ssl:/etc/apache2/ssl
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G 
  redis:
    image: redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
