version: '3'
services:
  laravel-app:
    build:
      context: .
    depends_on:
      - redis
    ports:
      - "8080:80"  # Mapeie a porta 80 do contêiner para a porta 8080 do host
      - "443:443"  # Mapeie a porta 443 do contêiner para a porta 443 do host
    env_file:
      - .env
    volumes:
      - ./ssl:/etc/apache2/ssl  # Mapeie a pasta 'ssl' local para '/etc/apache2/ssl' no contêiner

  redis:
    image: redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
