version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "9000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - php-fpm
    networks:
      - my_network

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - .env:/var/www/html/.env
    depends_on:
      - redis
    networks:
      - my_network

  redis:
    image: "redis:latest"
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    networks:
      - my_network
      
networks:
  my_network:
